// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: test

#include "../ui.h"

// COMPONENT Setting

lv_obj_t * ui_Setting_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Setting;
    cui_Setting = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_Setting, 460);
    lv_obj_set_height(cui_Setting, 30);
    lv_obj_set_x(cui_Setting, 0);
    lv_obj_set_y(cui_Setting, 10);
    lv_obj_set_align(cui_Setting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Setting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Setting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Setting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_Setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Setting, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SETTING_NUM);
    children[UI_COMP_SETTING_SETTING] = cui_Setting;
    lv_obj_add_event_cb(cui_Setting, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Setting, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Setting_create_hook(cui_Setting);
    return cui_Setting;
}

