// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: test

#ifndef _UI_COMP_SETTING_H
#define _UI_COMP_SETTING_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Setting
#define UI_COMP_SETTING_SETTING 0
#define _UI_COMP_SETTING_NUM 1
lv_obj_t * ui_Setting_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
